import 'dart:async'; // Timer ke liye
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:flutter_tts/flutter_tts.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:studybudy_ai/core/theme/app_colors.dart';
import 'package:studybudy_ai/features/summary/models/summary_model.dart';
import 'package:studybudy_ai/features/summary/services/summary_service.dart';
import 'package:studybudy_ai/features/summary/widgets/translation_selector.dart';
import 'package:studybudy_ai/features/summary/widgets/summary_chat_drawer.dart';
import 'package:studybudy_ai/features/summary/widgets/summary_document_viewer.dart';
import 'package:studybudy_ai/core/widgets/ai_processing_overlay.dart'; // Overlay Import (Optional for consistency)

class SummaryViewScreen extends StatefulWidget {
  final String fileContent;

  const SummaryViewScreen({super.key, required this.fileContent});

  @override
  State<SummaryViewScreen> createState() => _SummaryViewScreenState();
}

class _SummaryViewScreenState extends State<SummaryViewScreen> with SingleTickerProviderStateMixin {
  late Future<SummaryModel> _summaryFuture;
  final FlutterTts flutterTts = FlutterTts();
  late TabController _tabController;
  
  bool _isSpeaking = false;
  bool _isPdfGenerating = false;
  String _currentLang = "English";
  SummaryModel? _currentData; 

  // Loading Messages Logic
  int _loadingMsgIndex = 0;
  Timer? _loadingTimer;
  final List<String> _loadingMessages = [
    "Reading Document...",
    "Extracting Key Insights...",
    "Identifying Important Dates...",
    "Drafting Summary...",
    "Finalizing Format...",
  ];

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
    _summaryFuture = SummaryService().generateSummary(widget.fileContent);
    _startLoadingMessages(); // Start animation
  }

  @override
  void dispose() {
    _loadingTimer?.cancel();
    _tabController.dispose();
    super.dispose();
  }

  void _startLoadingMessages() {
    _loadingTimer = Timer.periodic(const Duration(seconds: 3), (timer) {
      if (!mounted) return;
      setState(() {
        _loadingMsgIndex = (_loadingMsgIndex + 1) % _loadingMessages.length;
      });
    });
  }

  // 📊 Calculate Stats
  int get _wordCount => _currentData?.summaryMarkdown.split(RegExp(r'\s+')).length ?? 0;
  int get _readingTime => (_wordCount / 200).ceil();

  // 📋 Copy
  void _handleCopy() {
    if (_currentData == null) return;
    Clipboard.setData(ClipboardData(text: _currentData!.summaryMarkdown));
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text("Summary copied!"), backgroundColor: Colors.green),
    );
  }

  // 🖨️ PDF
  Future<void> _handleDownloadPDF() async {
    if (_currentData == null) return;
    setState(() => _isPdfGenerating = true);

    try {
      final pdf = pw.Document();
      final font = await PdfGoogleFonts.merriweatherRegular();
      final titleFont = await PdfGoogleFonts.spaceGroteskBold();

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          theme: pw.ThemeData.withFont(base: font, bold: titleFont),
          build: (pw.Context context) {
            return [
              pw.Header(level: 0, child: pw.Text(_currentData!.title, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold))),
              pw.SizedBox(height: 10),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text("Generated by StudyBuddy AI", style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
                  pw.Text(DateTime.now().toString().split(' ')[0], style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
                ]
              ),
              pw.Divider(),
              pw.SizedBox(height: 20),
              pw.Paragraph(text: _currentData!.summaryMarkdown, style: const pw.TextStyle(fontSize: 12, lineSpacing: 5)),
            ];
          },
        ),
      );

      await Printing.sharePdf(bytes: await pdf.save(), filename: 'Summary_${_currentData!.title}.pdf');
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text("PDF Error: $e")));
    } finally {
      if (mounted) setState(() => _isPdfGenerating = false);
    }
  }

  // 🗣️ TTS
  Future<void> _toggleSpeech() async {
    if (_currentData == null) return;
    if (_isSpeaking) {
      await flutterTts.stop();
      setState(() => _isSpeaking = false);
    } else {
      setState(() => _isSpeaking = true);
      await flutterTts.setLanguage(_currentLang == 'Urdu' ? 'ur-PK' : 'en-US');
      await flutterTts.speak(_currentData!.summaryMarkdown);
      flutterTts.setCompletionHandler(() => setState(() => _isSpeaking = false));
    }
  }

  // 🌐 Translate
  void _handleTranslation(String lang) async {
    if (lang == _currentLang || _currentData == null) return;

    // Use Overlay for Translation too!
    try {
      final translatedText = await AIProcessingOverlay.show<String>(
        context: context,
        asyncTask: (updateStatus) async {
          updateStatus("Translating to $lang...");
          await Future.delayed(const Duration(seconds: 1)); // UX pause
          updateStatus("Polishing grammar...");
          
          return await SummaryService().translateSummary(
            _currentData!.summaryMarkdown, 
            lang
          );
        },
      );

      if (translatedText != null) {
        setState(() {
          _currentLang = lang;
          _currentData = SummaryModel(
            title: _currentData!.title,
            emoji: _currentData!.emoji,
            readingTime: _currentData!.readingTime,
            keyPoints: _currentData!.keyPoints, 
            summaryMarkdown: translatedText,
          );
        });
      }
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text("Error: $e")));
    }
  }

  // ✨ PROFESSIONAL LOADING SCREEN
  Widget _buildProfessionalLoader() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          // Lottie or Icon Animation
          Container(
            padding: const EdgeInsets.all(24),
            decoration: BoxDecoration(
              color: Colors.white,
              shape: BoxShape.circle,
              boxShadow: [
                BoxShadow(color: AppColors.primaryStart.withOpacity(0.2), blurRadius: 40, spreadRadius: 10)
              ]
            ),
            child: const CircularProgressIndicator(color: AppColors.primaryStart, strokeWidth: 3),
          ),
          const SizedBox(height: 30),
          
          // Animated Text
          AnimatedSwitcher(
            duration: const Duration(milliseconds: 500),
            child: Text(
              _loadingMessages[_loadingMsgIndex],
              key: ValueKey<String>(_loadingMessages[_loadingMsgIndex]),
              style: GoogleFonts.spaceGrotesk(
                fontSize: 20, 
                fontWeight: FontWeight.bold,
                color: AppColors.textDark
              ),
              textAlign: TextAlign.center,
            ),
          ),
          const SizedBox(height: 10),
          Text(
            "Powered by AI • Takes ~10-20s", 
            style: GoogleFonts.outfit(color: Colors.grey, fontSize: 12)
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey.shade100,
      body: FutureBuilder<SummaryModel>(
        future: _summaryFuture,
        builder: (context, snapshot) {
          
          // 1. LOADING STATE (Using new Design)
          if (snapshot.connectionState == ConnectionState.waiting) {
            return _buildProfessionalLoader();
          }
          
          if (snapshot.hasError) return Center(child: Text("Error: ${snapshot.error}"));
          
          if (snapshot.hasData && _currentData == null) {
            _currentData = snapshot.data;
            _loadingTimer?.cancel(); // Stop cycling messages
          }
          
          final data = _currentData!;

          // 2. MAIN CONTENT
          return NestedScrollView(
            headerSliverBuilder: (context, innerBoxIsScrolled) => [
              SliverAppBar(
                expandedHeight: 200,
                pinned: true,
                backgroundColor: AppColors.primaryStart,
                leading: IconButton(
                  icon: const Icon(Icons.arrow_back, color: Colors.white),
                  onPressed: () => Navigator.pop(context),
                ),
                actions: [
                  IconButton(icon: const Icon(Icons.copy, color: Colors.white), onPressed: _handleCopy, tooltip: "Copy"),
                  IconButton(
                    icon: _isPdfGenerating 
                      ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2)) 
                      : const Icon(Icons.download, color: Colors.white), 
                    onPressed: _isPdfGenerating ? null : _handleDownloadPDF,
                    tooltip: "Download PDF",
                  ),
                  IconButton(
                    icon: Icon(_isSpeaking ? Icons.stop_circle : Icons.volume_up, color: Colors.white),
                    onPressed: _toggleSpeech,
                    tooltip: "Listen",
                  ),
                  IconButton(
                    icon: const Icon(Icons.translate, color: Colors.white),
                    onPressed: () => _handleTranslation(_currentLang == 'English' ? 'Urdu' : 'English'), // Simple Toggle or show sheet
                    tooltip: "Translate",
                  ),
                ],
                flexibleSpace: FlexibleSpaceBar(
                  background: Container(
                    decoration: const BoxDecoration(
                      gradient: LinearGradient(colors: [AppColors.primaryStart, AppColors.primaryEnd]),
                    ),
                    child: Center(
                      child: ConstrainedBox(
                        constraints: const BoxConstraints(maxWidth: 800),
                        child: Padding(
                          padding: const EdgeInsets.symmetric(horizontal: 24.0),
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              const SizedBox(height: 30),
                              Text(data.emoji, style: const TextStyle(fontSize: 48)),
                              const SizedBox(height: 10),
                              Text(
                                data.title,
                                textAlign: TextAlign.center,
                                style: GoogleFonts.spaceGrotesk(
                                  fontSize: 24, 
                                  fontWeight: FontWeight.bold, 
                                  color: Colors.white
                                ),
                              ),
                              const SizedBox(height: 8),
                              Container(
                                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
                                decoration: BoxDecoration(
                                  color: Colors.white.withOpacity(0.2),
                                  borderRadius: BorderRadius.circular(12),
                                ),
                                child: Text(
                                  "${data.readingTime} read • $_wordCount words", 
                                  style: const TextStyle(color: Colors.white, fontSize: 12)
                                ),
                              )
                            ],
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
                bottom: TabBar(
                  controller: _tabController,
                  indicatorColor: Colors.white,
                  indicatorWeight: 3,
                  labelColor: Colors.white,
                  labelStyle: GoogleFonts.outfit(fontWeight: FontWeight.bold),
                  unselectedLabelColor: Colors.white70,
                  tabs: const [Tab(text: "KEY POINTS"), Tab(text: "FULL DOCUMENT")],
                ),
              ),
            ],
            body: TabBarView(
              controller: _tabController,
              children: [
                Center(
                  child: ConstrainedBox(
                    constraints: const BoxConstraints(maxWidth: 850),
                    child: ListView.builder(
                      padding: const EdgeInsets.all(24),
                      itemCount: data.keyPoints.length,
                      itemBuilder: (context, index) {
                        return _buildKeyPointItem(index, data.keyPoints[index]);
                      },
                    ),
                  ),
                ),
                Center(
                  child: ConstrainedBox(
                    constraints: const BoxConstraints(maxWidth: 900),
                    child: SingleChildScrollView(
                      padding: const EdgeInsets.only(bottom: 100),
                      child: SummaryDocumentViewer(
                        fileName: "Document Content",
                        content: data.summaryMarkdown,
                        wordCount: _wordCount,
                        readingTime: _readingTime,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          );
        },
      ),
      
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () {
          showGeneralDialog(
            context: context,
            barrierDismissible: true,
            barrierLabel: "Chat",
            transitionDuration: const Duration(milliseconds: 300),
            pageBuilder: (context, a1, a2) => Align(
              alignment: Alignment.centerRight,
              child: ConstrainedBox(
                constraints: const BoxConstraints(maxWidth: 500),
                child: SummaryChatDrawer(documentContext: _currentData?.summaryMarkdown ?? widget.fileContent)
              ),
            ),
            transitionBuilder: (context, a1, a2, child) => SlideTransition(
              position: Tween(begin: const Offset(1, 0), end: Offset.zero).animate(CurvedAnimation(parent: a1, curve: Curves.easeOutQuart)),
              child: child,
            ),
          );
        },
        backgroundColor: AppColors.primaryStart,
        foregroundColor: Colors.white,
        elevation: 4,
        icon: const Icon(Icons.auto_awesome),
        label: const Text("Chat with AI"),
      ),
    );
  }

  Widget _buildKeyPointItem(int index, String text) {
    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(color: Colors.black.withOpacity(0.04), blurRadius: 10, offset: const Offset(0, 4))
        ],
        border: Border.all(color: Colors.grey.shade100),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: AppColors.primaryStart.withOpacity(0.1),
              shape: BoxShape.circle,
            ),
            child: Text(
              "${index + 1}",
              style: GoogleFonts.spaceGrotesk(
                fontSize: 16, 
                fontWeight: FontWeight.bold, 
                color: AppColors.primaryStart
              ),
            ),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Text(
              text,
              style: GoogleFonts.merriweather(
                fontSize: 16,
                height: 1.6,
                color: Colors.black87,
              ),
            ),
          ),
        ],
      ),
    );
  }
}